load libraries

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split

import dataset

In [5]:
cancer=pd.read_csv('C:\\Users\\aminy\\OneDrive\\Desktop\\breast cancer\\cancer.csv')
cancer

,id number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025.0,5,1,1,1,2,1,3,1,1,2
1,1002945.0,5,4,4,5,7,10,3,2,1,2
2,1015425.0,3,1,1,1,2,2,3,1,1,2
3,1016277.0,6,8,8,1,3,4,3,7,1,2
4,1017023.0,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715.0,3,1,1,1,3,2,1,1,1,2
695,841769.0,2,1,1,1,2,1,1,1,1,2
696,888820.0,5,10,10,3,7,3,8,10,2,4
697,897471.0,4,8,6,4,3,4,10,6,1,4
698,897471.0,4,8,8,5,4,5,10,4,1,4

cleaning data

In [6]:
cancer.columns

Index(['id number    ', 'Clump Thickness ', 'Uniformity of Cell Size',
       'Uniformity of Cell Shape', 'Marginal Adhesion',
       'Single  Epithelial Cell Size', 'Bare  Nuclei', 'Bland Chromatin',
       'Normal Nucleoli  ', 'Mitoses', 'Class'],
      dtype='object')

In [7]:
#Dropping ID column
cancer=cancer.drop('id number    ',axis=1)

#Show Key Statistics
cancer.describe().T

,count,mean,std,min,25%,50%,75%,max
Clump Thickness,699.0,4.417740,2.815741,1.0,2.0,4.0,6.0,10.0
Uniformity of Cell Size,699.0,3.134478,3.051459,1.0,1.0,1.0,5.0,10.0
Uniformity of Cell Shape,699.0,3.207439,2.971913,1.0,1.0,1.0,5.0,10.0
Marginal Adhesion,699.0,2.806867,2.855379,1.0,1.0,1.0,4.0,10.0
Single Epithelial Cell Size,699.0,3.216023,2.214300,1.0,2.0,2.0,4.0,10.0
Bland Chromatin,699.0,3.437768,2.438364,1.0,2.0,3.0,5.0,10.0
Normal Nucleoli,699.0,2.866953,3.053634,1.0,1.0,1.0,4.0,10.0
Mitoses,699.0,1.589413,1.715078,1.0,1.0,1.0,1.0,10.0
Class,699.0,2.689557,0.951273,2.0,2.0,2.0,4.0,4.0

In [8]:
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import MinMaxScaler
# The dataset contains missing values.We will replace those "?"s with 0's
cancer.replace('?',0, inplace=True)

#The "?"s are replaced with 0's now. Let's do the missing value treatment now.
# Convert the DataFrame object into NumPy array otherwise you will not be able to impute
values = cancer.values

# Now impute it
#imputer = SimpleImputerImputer()
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputedData = imputer.fit_transform(values)

scaler = MinMaxScaler(feature_range=(0, 1))
normalizedData = scaler.fit_transform(imputedData)

define X & Y

In [11]:
X = normalizedData[:,:-1]
y = normalizedData[:,-1]


# ensure all data are floating point values
X = X.astype('float32')
# encode strings to integer
#y = LabelEncoder().fit_transform(y)
# split into train and test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
# determine the number of input features
n_features = X_train.shape[1]
print(n_features)

(559, 9) (140, 9) (559,) (140,)
9